# culture="en-US"
ConvertFrom-StringData -StringData @'
ErrorModuleFailedToImportFunction=Failed to import function: {0}: {1}
VerboseListingParametersUtilized=Listing Parameters utilized:
GetPreferenceUsingDefaults=No preferences are set. Currently using default values.
SuitTrump=Trump
SuitPentacles=Pentacles
SuitDiscs=Discs
SuitCoins=Coins
SuitWands=Wands
SuitRods=Rods
SuitStaves=Staves
SuitCups=Cups
SuitChalices=Chalices
SuitGoblets=Goblets
SuitSwords=Swords
SuitBlades=Blades
SuitAthames=Athames
CardAce=Ace
CardTwo=Two
CardThree=Three
CardFour=Four
CardFive=Five
CardSix=Six
CardSeven=Seven
CardEight=Eight
CardNine=Nine
CardTen=Ten
CardPage=Page
CardKnight=Knight
CardQueen=Queen
CardKing=King
Card0=The Fool
CardI=The Magician
CardII=The High Priestess
CardIII=The Empress
CardIV=The Emperor
CardV=The Hierophant
CardVI=The Lovers
CardVII=The Chariot
CardVIII=Justice
CardIX=The Hermit
CardX=Wheel of Fortune
CardXI=Strength
CardXII=The Hanged Man
CardXIII=Death
CardXIV=Temperance
CardXV=The Devil
CardXVI=The Tower
CardXVII=The Star
CardXVIII=The Moon
CardXIX=The Sun
CardXX=Judgement
CardXXI=The World
'@